## Agregaciones Semanales 

#### Este notebook tiene como objetivo generar las tablas de las variables climaticas por semana

In [1]:
pwd

'd:\\OneDrive - CGIAR\\Proyectos\\AgriLAC-ICC\\ICC\\Scrip_bases'

In [2]:
## Libreías generales
import numpy as np
import pandas as pd
import datetime
from dateutil.relativedelta import relativedelta

In [3]:
#comando para visualizar todas las columnas del df
pd.pandas.set_option('display.max_columns', None)

In [5]:
#### Carga de información de las estaciones
info_estaciones = pd.read_excel('prueba_info.xlsx')

,No.,Estacion,Codigo,Tipo,Resolución\ntemporal *,Fecha de inicio,Años,Longitud,Latitud,Altitud\n(msnm),Estrato,t,LUGAR,RESPONSABLE,Temperatura,Radiación,Humedad Relativa,Precipitación pluvial,Mojadura\nde la hoja,Velocidad y dirección del viento,Presión\natmosférica,Brillo\nsolar
0,1,Cengicaña,CEN-CEN,Automática GPRS,15 minutos,1997-11-19,24.931507,-91.055468,14.330962,297,Alto,Alto,Santa Lucía Cotz. Escuintla,ICC,Si,Si,Si,Si,Si,Si,No,Si
1,2,Tehuantepec,LUT-TEH,Automática GPRS,15 minutos,1998-03-04,24.643836,-91.103443,14.168625,67,Bajo,Bajo,Santa Lucia Cotz. Escuintla,La Unión,Si,Si,Si,Si,Si,Si,No,No
2,3,El Bálsamo,PAN-BAL,Automática GPRS,15 minutos,2002-02-13,20.693151,-91.003744,14.281468,280,Medio,Medio,Santa Lucía Cotz. Escuintla,Ingenio Pantaleón,Si,Si,Si,Si,Si,Si,No,No
3,4,Puyumate,TBU-PUY,Automática GPRS,15 minutos,2002-02-14,20.690411,-91.259910,14.261557,77,Bajo,Bajo,"Nueva Concepción, Escuintla",Ingenio Pantaleón,Si,Si,Si,Si,Si,Si,No,No
4,5,San Antonio el Valle,MAG-SAV,Automática GPRS,15 minutos,2002-02-27,20.654795,-91.200961,13.995364,10,Litoral,Litoral,"La Gomera, Escuintla",Ingenio Magdalena,Si,Si,Si,Si,Si,Si,No,No

In [6]:

####Limpieza de la base  de datos para eliminar caracteres especiales 

info_estaciones.Codigo =info_estaciones.Codigo.replace(r'\W+', '', regex=True)
info_estaciones.Codigo = info_estaciones.Codigo.replace(r'\s+', ' ', regex=True)
info_estaciones.Codigo = info_estaciones.Codigo.replace("", np.nan, regex=True)
info_estaciones.Codigo= info_estaciones.Codigo.replace(" ", np.nan, regex=True)

,No.,Estacion,Codigo,Tipo,Resolución\ntemporal *,Fecha de inicio,Años,Longitud,Latitud,Altitud\n(msnm),Estrato,t,LUGAR,RESPONSABLE,Temperatura,Radiación,Humedad Relativa,Precipitación pluvial,Mojadura\nde la hoja,Velocidad y dirección del viento,Presión\natmosférica,Brillo\nsolar
0,1,Cengicaña,CENCEN,Automática GPRS,15 minutos,1997-11-19,24.931507,-91.055468,14.330962,297,Alto,Alto,Santa Lucía Cotz. Escuintla,ICC,Si,Si,Si,Si,Si,Si,No,Si
1,2,Tehuantepec,LUTTEH,Automática GPRS,15 minutos,1998-03-04,24.643836,-91.103443,14.168625,67,Bajo,Bajo,Santa Lucia Cotz. Escuintla,La Unión,Si,Si,Si,Si,Si,Si,No,No
2,3,El Bálsamo,PANBAL,Automática GPRS,15 minutos,2002-02-13,20.693151,-91.003744,14.281468,280,Medio,Medio,Santa Lucía Cotz. Escuintla,Ingenio Pantaleón,Si,Si,Si,Si,Si,Si,No,No
3,4,Puyumate,TBUPUY,Automática GPRS,15 minutos,2002-02-14,20.690411,-91.259910,14.261557,77,Bajo,Bajo,"Nueva Concepción, Escuintla",Ingenio Pantaleón,Si,Si,Si,Si,Si,Si,No,No
4,5,San Antonio el Valle,MAGSAV,Automática GPRS,15 minutos,2002-02-27,20.654795,-91.200961,13.995364,10,Litoral,Litoral,"La Gomera, Escuintla",Ingenio Magdalena,Si,Si,Si,Si,Si,Si,No,No

In [7]:

### Se seleccionan de la base info_estaciones, las columnas que se van a utilizar 

info_estrato =info_estaciones[['Estacion','Codigo','t']]
info_estrato.columns = ['nombre_estacion','estacion','estrato']
#info_estrato.to_excel('info_estratos.xlsx')

In [8]:
"""
Se crea un diccionario con las abreviaturas de los nombres de cada estación

"""

dict_esta= {'CEN':"CENCEN",'TEH':"LUTTEH", 'BAL':"PANBAL", 'PUY':"TBUPUY", 'SAV':"MAGSAV", 'AMA':"SAAAMA",
             'TRI':"SDTTRI", 'IRL':"TBUIRL", 'BON':"LUTBON", 'BOU':"MAGBOU", 'NRJ':"PAGNRJ", 'PEO':"MATPEO",
             'CBR':"SDTCBR", 'TLA': "TULTLA", 'LOR':"PAGLOR" , 'SRF':"PANSRF", 'XOL':"MAGXOL", 'SNC':"MAGSNC",
             'TMG':"MAGTMG", 'PLT':"ICCPLT",  'LGR':"SAALGR", 'CDL':"ICCCDL",  'CHI':"ICCCHI", 'PVD':"MAGPVD", 
             'ALA':"ICCALA", 'COC':"PAGCOC", 'CON':"ICCCON", 'LMQ':"SAALMQ", 'STA':"ICCSTA", 'YEPO':"ICCYEPO",
             'CIZ':"CASSACIZ",'CPL':"CASSACPL", 'CPT':"ASSACPT", 'ECA':"CASSAECA", 'SCL':"CASSASCL", 'AGS':"CASSAAGS",
             'PBR':"ICCPBR", 'MTA':"ICCMTA", 'TUL': "TULTLA", 'NAR': "PAGNRJ", 'LCD':"ICCCDL", 'CASSACPT':"ASSACPT"
}

In [9]:
### Se carga el archivo que se guardo de los calculos de las variables diarias

df_diario = pd.read_parquet('diario_complete.parquet')

,estacion,date,semana,dia,mes,año,temperatura_min_diaria,temperatura_max_diaria,temperatura_promedio_diaria,radiacion_diaria_acumulada,radiacion_diaria_promedio,humedad_relativa_min_diaria,humedad_relativa_max_diaria,humedad_relativa_media_diaria,lluvia_diaria,velocidad_viento_media_diario,velocidad_viento_max_diaria,amplitud_termica,radiacion_global,radiacion_dia_despejado,N Daylight hours,Ra,estacion_resume,altitud,estrato,latitud,longitud,latitud_rad,radiacion_media_estimada Heargreaves,Rg,n,dia_juliano,dr,declinacion,ang_horario_puesta_sol,heliofania,ra_MJm-2day-1,radiacion_solar_piranometro,constante_psicometrica,pendiente_curva_presion_satu_vapor,presion_saturacion_vapor,presion_real_vapor,deficit_presion_vapor,rns,rnl,rn,velocidad_viento_altura_standar,FAO-Penman-Montieth,deficit
0,CENCEN,2008-06-11,24,11,6,2008,19.4,31.9,25.094792,24413.6,254.308333,52.0,93.0,76.666667,2.6,4.514583,21.1,12.5,442.9,334.7,12.828,38.185,CEN,300,Alto,14.330962,-91.055468,0.250122,250.542075,21.894361,7.737019,163,0.968842,0.404105,1.680265,12.836249,38.200705,21.97224,0.065039,0.146299,3.490402,2.121480,1.368922,16.918625,3.611187,13.307438,0.937969,0.420380,2.179620
1,CENCEN,2009-06-11,24,11,6,2009,21.2,32.7,25.609375,26112.4,272.004167,58.0,96.0,81.541667,9.4,7.118750,29.6,11.5,442.9,334.7,12.828,38.185,CEN,300,Alto,14.330962,-91.055468,0.250122,240.311516,23.417861,8.561034,162,0.969033,0.402959,1.679917,12.833590,38.208086,23.50116,0.065039,0.150321,3.731921,2.450758,1.281163,18.095893,3.604390,14.491503,1.479021,0.415315,8.984685
2,CENCEN,2010-06-11,23,11,6,2010,22.1,32.5,26.316667,22499.4,234.368750,53.0,95.0,78.062500,1.2,3.218750,20.0,10.4,442.9,334.7,12.828,38.185,CEN,300,Alto,14.330962,-91.055468,0.250122,228.529533,20.177687,6.808524,162,0.969033,0.402959,1.679917,12.833590,38.208086,20.24946,0.065039,0.156002,3.775434,2.352183,1.423251,15.592084,2.990995,12.601089,0.668741,0.443173,0.756827
3,CENCEN,2011-06-11,23,11,6,2011,22.1,32.7,26.965625,19675.1,204.948958,57.0,96.0,78.562500,4.8,2.257292,10.1,10.6,442.9,334.7,12.828,38.185,CEN,300,Alto,14.330962,-91.055468,0.250122,230.716469,17.644826,5.438578,162,0.969033,0.402959,1.679917,12.833590,38.208086,17.70759,0.065039,0.161373,3.803104,2.476888,1.326216,13.634844,2.290996,11.343848,0.468984,0.426577,4.373423
4,CENCEN,2012-06-11,24,11,6,2012,22.2,32.5,26.411458,17912.7,186.590625,53.0,91.0,76.812500,0.0,2.130208,21.1,10.3,442.9,334.7,12.828,38.185,CEN,300,Alto,14.330962,-91.055468,0.250122,227.428180,16.064288,4.583714,163,0.968842,0.404105,1.680265,12.836249,38.200705,16.12143,0.065039,0.156777,3.783556,2.313200,1.470357,12.413501,2.054312,10.359189,0.442581,0.394058,-0.394058

In [10]:
"""
Se realiza el reemplazo de las abrevituras a partir del diccionario creado

"""
df_diario.replace({"estacion": dict_esta},inplace=True)

## Join
#### Se cruzan las bases de datos de información de las estaciones junto con la base de datos general diaria

In [12]:
"""
Se cruza la base de info de las estaciones y la base de datos completa para agregar el estrato 

"""
df_diario=df_diario.merge(info_estrato, how='right', on=['estacion', 'estrato'])
df_diario.head()

,estacion,date,semana,dia,mes,año,temperatura_min_diaria,temperatura_max_diaria,temperatura_promedio_diaria,radiacion_diaria_acumulada,radiacion_diaria_promedio,humedad_relativa_min_diaria,humedad_relativa_max_diaria,humedad_relativa_media_diaria,lluvia_diaria,velocidad_viento_media_diario,velocidad_viento_max_diaria,amplitud_termica,radiacion_global,radiacion_dia_despejado,N Daylight hours,Ra,estacion_resume,altitud,estrato,latitud,longitud,latitud_rad,radiacion_media_estimada Heargreaves,Rg,n,dia_juliano,dr,declinacion,ang_horario_puesta_sol,heliofania,ra_MJm-2day-1,radiacion_solar_piranometro,constante_psicometrica,pendiente_curva_presion_satu_vapor,presion_saturacion_vapor,presion_real_vapor,deficit_presion_vapor,rns,rnl,rn,velocidad_viento_altura_standar,FAO-Penman-Montieth,deficit,nombre_estacion
0,CENCEN,2008-06-11,24.0,11.0,6.0,2008.0,19.4,31.9,25.094792,24413.6,254.308333,52.0,93.0,76.666667,2.6,4.514583,21.1,12.5,442.9,334.7,12.828,38.185,CEN,300.0,Alto,14.330962,-91.055468,0.250122,250.542075,21.894361,7.737019,163.0,0.968842,0.404105,1.680265,12.836249,38.200705,21.97224,0.065039,0.146299,3.490402,2.121480,1.368922,16.918625,3.611187,13.307438,0.937969,0.420380,2.179620,Cengicaña
1,CENCEN,2009-06-11,24.0,11.0,6.0,2009.0,21.2,32.7,25.609375,26112.4,272.004167,58.0,96.0,81.541667,9.4,7.118750,29.6,11.5,442.9,334.7,12.828,38.185,CEN,300.0,Alto,14.330962,-91.055468,0.250122,240.311516,23.417861,8.561034,162.0,0.969033,0.402959,1.679917,12.833590,38.208086,23.50116,0.065039,0.150321,3.731921,2.450758,1.281163,18.095893,3.604390,14.491503,1.479021,0.415315,8.984685,Cengicaña
2,CENCEN,2010-06-11,23.0,11.0,6.0,2010.0,22.1,32.5,26.316667,22499.4,234.368750,53.0,95.0,78.062500,1.2,3.218750,20.0,10.4,442.9,334.7,12.828,38.185,CEN,300.0,Alto,14.330962,-91.055468,0.250122,228.529533,20.177687,6.808524,162.0,0.969033,0.402959,1.679917,12.833590,38.208086,20.24946,0.065039,0.156002,3.775434,2.352183,1.423251,15.592084,2.990995,12.601089,0.668741,0.443173,0.756827,Cengicaña
3,CENCEN,2011-06-11,23.0,11.0,6.0,2011.0,22.1,32.7,26.965625,19675.1,204.948958,57.0,96.0,78.562500,4.8,2.257292,10.1,10.6,442.9,334.7,12.828,38.185,CEN,300.0,Alto,14.330962,-91.055468,0.250122,230.716469,17.644826,5.438578,162.0,0.969033,0.402959,1.679917,12.833590,38.208086,17.70759,0.065039,0.161373,3.803104,2.476888,1.326216,13.634844,2.290996,11.343848,0.468984,0.426577,4.373423,Cengicaña
4,CENCEN,2012-06-11,24.0,11.0,6.0,2012.0,22.2,32.5,26.411458,17912.7,186.590625,53.0,91.0,76.812500,0.0,2.130208,21.1,10.3,442.9,334.7,12.828,38.185,CEN,300.0,Alto,14.330962,-91.055468,0.250122,227.428180,16.064288,4.583714,163.0,0.968842,0.404105,1.680265,12.836249,38.200705,16.12143,0.065039,0.156777,3.783556,2.313200,1.470357,12.413501,2.054312,10.359189,0.442581,0.394058,-0.394058,Cengicaña

In [13]:
"""
Se eliminan las estaciones del salvador dado que no se incluyen en los boletines que realizan en ICC las cuales son: 
CIZ:CASSACIZ, 'CPL':"CASSACPL", 'SCL':"CASSASCL", 'AGS':"CASSAAGS",'CPT':"ASSACPT" y 'ECA':"CASSAECA"
A su vez se elimnan las estaciones 'PLT':"ICCPLT", 'STA':"ICCSTA", 'PBR':"ICCPBR" y 'YEPO':"ICCYEPO", 
dado que los reportes que realizan desde ICC solo incluyen las estaciones de zonas cañeras, 
por lo tanto se reportan 28 estaciones 

"""

to_remove = df_diario.loc[df_diario.estacion.isin(["CASSACIZ","CASSACPL","CASSASCL","CASSAAGS","CASSACPT",
                           "CASSAECA","ICCPLT","ICCPBR","ICCSTA","ICCYEPO"])].index

df_diario.drop(to_remove, inplace=True)

### Base de datos brillo solar

In [14]:
'Se crea una base de datos que contiene por estación el acumulado por semana de brillo solar  '

Brillo_solar= df_diario.groupby(['estacion', 'semana','año','estrato']).agg(n_brillo_solar_acum=('n', 'sum')).round(2).reset_index()
Brillo_solar=Brillo_solar.astype({'semana':int, 'año':int})
#Brillo_solar[(Brillo_solar.estacion=='CENCEN')& (Brillo_solar.año==2022)]

In [15]:
'Esta base tiene la variable de brillo solar promedio por estrato y por semana'

n_brillo_estra =Brillo_solar.groupby(['estrato','semana','año']).mean().reset_index()
n_brillo_estra.head()

C:\Users\darias\AppData\Local\Temp\ipykernel_4432\1501121354.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  n_brillo_estra =Brillo_solar.groupby(['estrato','semana','año']).mean().reset_index()

  estrato  semana   año  n_brillo_solar_acum
0    Alto       1  2007                 5.52
1    Alto       1  2008                61.32
2    Alto       1  2009                27.71
3    Alto       1  2010                40.60
4    Alto       1  2011                49.19

### Calculos de las variables semanales

In [16]:
#df_semanal
df_semanal = df_diario.groupby(['estrato','semana','año']).agg(
    temp_min_semanal=('temperatura_min_diaria', 'mean'),
    temp_max_semanal=('temperatura_max_diaria', 'mean'),
    temp_promedio_semanal=('temperatura_promedio_diaria', 'mean'),
    rad_diar_prom_semanal=('radiacion_diaria_promedio', 'mean'),
    ampl_term_prom_semanal = ('amplitud_termica', 'mean'),
    hume_rela_med_semanal= ('humedad_relativa_media_diaria','mean'),
    Veloc_viento_prom_max_semanal= ('velocidad_viento_max_diaria', 'mean'),
    Veloc_viento_media_semanal= ('velocidad_viento_media_diario', 'mean' ),
    max_lluvia=('lluvia_diaria', 'max'),
    acumu_lluvia=('lluvia_diaria', 'sum')

).reset_index().round(2).astype({'semana':int, 'año':int})

,estrato,semana,año,temp_min_semanal,temp_max_semanal,temp_promedio_semanal,rad_diar_prom_semanal,ampl_term_prom_semanal,hume_rela_med_semanal,Veloc_viento_prom_max_semanal,Veloc_viento_media_semanal,max_lluvia,acumu_lluvia
0,Alto,1,2007,18.90,32.10,24.75,170.07,13.20,72.50,17.90,5.31,0.0,0.0
1,Alto,1,2008,18.62,32.78,24.87,194.77,14.16,63.39,38.88,12.18,0.0,0.0
2,Alto,1,2009,17.25,32.02,23.99,196.95,14.77,70.05,21.15,5.74,0.0,0.0
3,Alto,1,2010,18.34,32.50,24.50,176.98,14.16,70.90,22.46,4.55,24.6,24.6
4,Alto,1,2011,18.44,31.36,24.31,199.76,12.92,73.12,14.10,4.06,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3099,Medio,53,2010,20.57,32.60,25.82,193.73,12.03,71.69,18.85,6.97,0.0,0.0
3100,Medio,53,2015,20.82,33.88,26.50,177.70,13.07,79.12,11.69,5.31,0.0,0.0
3101,Medio,53,2016,21.50,34.20,26.72,170.34,12.70,82.82,13.23,5.12,8.2,8.2
3102,Medio,53,2020,19.08,31.34,24.30,203.61,12.26,79.88,12.61,5.26,4.6,9.8
3103,Medio,53,2021,20.96,31.34,25.56,199.07,10.38,85.00,11.73,5.16,0.2,0.2

### Join

In [17]:
'Se cruza la base de datos de brillo solar semanal y la base con las demas variables semanales'
df_semanal=n_brillo_estra.merge(df_semanal,how='inner', on=['estrato','semana','año'])

,estrato,semana,año,n_brillo_solar_acum,temp_min_semanal,temp_max_semanal,temp_promedio_semanal,rad_diar_prom_semanal,ampl_term_prom_semanal,hume_rela_med_semanal,Veloc_viento_prom_max_semanal,Veloc_viento_media_semanal,max_lluvia,acumu_lluvia
0,Alto,1,2007,5.52,18.90,32.10,24.75,170.07,13.20,72.50,17.90,5.31,0.0,0.0
1,Alto,1,2008,61.32,18.62,32.78,24.87,194.77,14.16,63.39,38.88,12.18,0.0,0.0
2,Alto,1,2009,27.71,17.25,32.02,23.99,196.95,14.77,70.05,21.15,5.74,0.0,0.0
3,Alto,1,2010,40.60,18.34,32.50,24.50,176.98,14.16,70.90,22.46,4.55,24.6,24.6
4,Alto,1,2011,49.19,18.44,31.36,24.31,199.76,12.92,73.12,14.10,4.06,0.0,0.0

### Base de datos precipitación

In [18]:
'Se construye la base de datos para precipitación, en cuanto a la sumatoria agrupando por estacio, estrato, semana y año'


precip= df_diario.groupby(['estacion','estrato', 'semana','año']).agg(preci_semana=('lluvia_diaria', 'sum')).reset_index().astype({'semana':int, 'año':int})

  estacion estrato  semana   año  preci_semana
0   CENCEN    Alto       1  2007           0.0
1   CENCEN    Alto       1  2008           0.0
2   CENCEN    Alto       1  2009           0.0
3   CENCEN    Alto       1  2010          24.6
4   CENCEN    Alto       1  2011           0.0

In [19]:
'Despues de construir dicha base de precipitación se construye una base de datos del promedio de la precipitación clasificada pot estratos'

prec_prom_estra =precip.groupby(['estrato','semana','año']).mean().reset_index().round(2).astype({'semana':int, 'año':int})

C:\Users\darias\AppData\Local\Temp\ipykernel_4432\2045831608.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  prec_prom_estra =precip.groupby(['estrato','semana','año']).mean().reset_index().round(2).astype({'semana':int, 'año':int})

  estrato  semana   año  preci_semana
0    Alto       1  2007           0.0
1    Alto       1  2008           0.0
2    Alto       1  2009           0.0
3    Alto       1  2010          24.6
4    Alto       1  2011           0.0

In [21]:
prec_prom_estra["prec_acumulada"] = prec_prom_estra.groupby(['estrato','año'])["preci_semana"].cumsum().round(2)

  estrato  semana   año  preci_semana  prec_acumulada
0    Alto       1  2007           0.0             0.0
1    Alto       1  2008           0.0             0.0
2    Alto       1  2009           0.0             0.0
3    Alto       1  2010          24.6            24.6
4    Alto       1  2011           0.0             0.0

In [22]:
prec_prom_estra[(prec_prom_estra.año==2022)&(prec_prom_estra.estrato=="Alto")]

    estrato  semana   año  preci_semana  prec_acumulada
15     Alto       1  2022         26.40           26.40
30     Alto       2  2022         11.53           37.93
45     Alto       3  2022          0.00           37.93
60     Alto       4  2022         11.60           49.53
75     Alto       5  2022         33.67           83.20
90     Alto       6  2022         11.93           95.13
105    Alto       7  2022          0.20           95.33
120    Alto       8  2022          0.00           95.33
135    Alto       9  2022          6.87          102.20
150    Alto      10  2022         11.60          113.80
165    Alto      11  2022         17.40          131.20
180    Alto      12  2022         66.27          197.47
195    Alto      13  2022         35.53          233.00
210    Alto      14  2022         38.87          271.87
225    Alto      15  2022         28.27          300.14
240    Alto      16  2022        109.73          409.87
255    Alto      17  2022        121.40          531.27
270    Alto      18  2022        122.80          654.07
285    Alto      19  2022         40.53          694.60
300    Alto      20  2022        260.47          955.07
315    Alto      21  2022        160.60         1115.67
330    Alto      22  2022        128.53         1244.20
345    Alto      23  2022         85.20         1329.40
360    Alto      24  2022        146.20         1475.60
375    Alto      25  2022        195.20         1670.80
390    Alto      26  2022         22.40         1693.20
405    Alto      27  2022         57.40         1750.60
420    Alto      28  2022        119.07         1869.67
435    Alto      29  2022         86.27         1955.94
450    Alto      30  2022        188.73         2144.67
465    Alto      31  2022         69.53         2214.20
480    Alto      32  2022        105.73         2319.93
769    Alto      52  2022          0.00         2319.93

In [23]:
'Se cruza la base de datos de precipitacion semanal y la base con las demas variables semanales'
df_semanal=prec_prom_estra.merge(df_semanal,how='inner', on=['estrato','semana','año'])

In [24]:
"""Se guarda la  base de datos con las variables calculadas semanalmente, en este caso se guarda en formato parquet dado
que este formato es mas liviano que descargar la bae en un excel, pero tambien es posible guardar en formato excel"""

df_semanal.to_parquet('semanal_complete.parquet')

#df_semanal.to_excel('semanal_complate.excel')